import type { ElectricalItemRow } from "@/lib/electrical-item-types";
import type { DetectedRoomRow } from "@/lib/detected-room-types";
import type { SavedScanRow } from "@/lib/saved-scan-types";
import { parseScanItems, parseScanRooms } from "@/lib/saved-scan-types";
import {
  displayWhichRoom,
  itemMatchesDetectedRoom,
  normalizeRoomLabel,
} from "@/lib/room-item-match";

const COMPANY = "TPP Electric";
const FOOTER = "Generated by Blueprint AI";

function csvEscape(s: string): string {
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function buildScanCsv(
  scan: SavedScanRow,
  scanNotesForRows: string,
): string {
  const items = parseScanItems(scan.items_snapshot);
  const headers = [
    "Category",
    "Description",
    "Specification",
    "Claude Count",
    "GPT Count",
    "Manual Count",
    "Final Count",
    "Confidence",
    "Page Number",
    "Verification Status",
    "Notes",
  ];
  const lines = [headers.join(",")];
  for (const i of items) {
    const gpt = i.gpt_count;
    const finalC = i.final_count;
    const manualCol =
      i.verification_status === "manual" && finalC != null
        ? String(finalC)
        : "";
    const row = [
      csvEscape(String(i.category ?? "")),
      csvEscape(String(i.description ?? "")),
      csvEscape(String(i.specification ?? "")),
      String(i.quantity ?? ""),
      gpt != null ? String(gpt) : "",
      manualCol,
      finalC != null ? String(finalC) : "",
      String(i.confidence ?? ""),
      String(i.page_number ?? scan.page_number),
      csvEscape(String(i.verification_status ?? "")),
      csvEscape(scanNotesForRows),
    ];
    lines.push(row.join(","));
  }
  return lines.join("\r\n");
}

export function buildScanPlainText(
  scan: SavedScanRow,
  projectName: string,
): string {
  const items = parseScanItems(scan.items_snapshot);
  const rooms = parseScanRooms(scan.rooms_snapshot);
  const lines: string[] = [
    `${COMPANY} — Takeoff summary`,
    `Project: ${projectName}`,
    `Scan: ${scan.scan_name}`,
    `Date: ${new Date(scan.scan_date).toLocaleString()}`,
    `Page: ${scan.page_number}`,
    `Total item lines: ${scan.total_items}`,
    scan.notes ? `Scan notes: ${scan.notes}` : "",
    "",
    "ROOMS",
    ...rooms.map(
      (r) =>
        `- ${r.room_name} (${r.room_type})${r.sq_ft != null ? ` ~${r.sq_ft} sq ft` : ""}`,
    ),
    "",
    "ITEMS",
    ...items.map(
      (i) =>
        `- [${i.category}] ${i.description} × ${i.quantity} ${i.unit} (conf ${Number(i.confidence).toFixed(2)}, status ${i.verification_status ?? "—"})`,
    ),
    "",
    FOOTER,
  ];
  return lines.filter(Boolean).join("\n");
}

export async function copyScanTextToClipboard(text: string): Promise<void> {
  await navigator.clipboard.writeText(text);
}

export function openScanPrintableReport(
  scan: SavedScanRow,
  projectName: string,
): void {
  const items = parseScanItems(scan.items_snapshot);
  const rooms = parseScanRooms(scan.rooms_snapshot);
  const lowConf = items.filter((i) => Number(i.confidence) < 0.7);

  const roomRows = rooms
    .map(
      (r) =>
        `<tr><td>${escapeHtml(r.room_name)}</td><td>${escapeHtml(r.room_type)}</td><td>${r.sq_ft != null ? escapeHtml(String(r.sq_ft)) : "—"}</td></tr>`,
    )
    .join("");

  const itemRows = items
    .map(
      (i) =>
        `<tr class="${Number(i.confidence) < 0.7 ? "low" : ""}"><td>${escapeHtml(i.category)}</td><td>${escapeHtml(i.description)}</td><td>${escapeHtml(i.specification)}</td><td class="num">${i.quantity}</td><td class="num">${Number(i.confidence).toFixed(2)}</td><td>${escapeHtml(String(i.verification_status ?? ""))}</td></tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${escapeHtml(scan.scan_name)}</title>
<style>
body{font-family:system-ui,sans-serif;max-width:900px;margin:24px auto;color:#111;line-height:1.4}
h1{font-size:1.35rem} h2{font-size:1.05rem;margin-top:1.25rem}
.meta{color:#444;font-size:0.9rem}
table{width:100%;border-collapse:collapse;font-size:0.88rem}
th,td{border:1px solid #ccc;padding:6px 8px;text-align:left}
th{background:#f0f0f0}
tr.low{background:#fff9c4}
.num{text-align:right}
footer{margin-top:2rem;font-size:0.8rem;color:#666;border-top:1px solid #ddd;padding-top:8px}
</style></head><body>
<h1>${escapeHtml(COMPANY)}</h1>
<p class="meta"><strong>Project:</strong> ${escapeHtml(projectName)}<br/>
<strong>Scan:</strong> ${escapeHtml(scan.scan_name)}<br/>
<strong>Date:</strong> ${escapeHtml(new Date(scan.scan_date).toLocaleString())}<br/>
<strong>Page:</strong> ${scan.page_number}</p>
<h2>Room summary</h2>
<table><thead><tr><th>Room</th><th>Type</th><th>Sq ft</th></tr></thead><tbody>${roomRows || "<tr><td colspan='3'>No rooms in snapshot</td></tr>"}</tbody></table>
<h2>Itemized list (by line)</h2>
<table><thead><tr><th>Category</th><th>Description</th><th>Specification</th><th>Qty</th><th>Conf.</th><th>Status</th></tr></thead><tbody>${itemRows || "<tr><td colspan='6'>No items</td></tr>"}</tbody></table>
${lowConf.length ? `<h2>Low confidence flags</h2><ul>${lowConf.map((i) => `<li>${escapeHtml(i.description)} (${Number(i.confidence).toFixed(2)})</li>`).join("")}</ul>` : ""}
${scan.notes ? `<h2>Plan notes / scan notes</h2><p>${escapeHtml(scan.notes)}</p>` : ""}
<footer>${escapeHtml(FOOTER)}</footer>
<script>window.onload=function(){ window.focus(); }</script>
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) {
    window.alert("Pop-up blocked. Allow pop-ups to print the report.");
    return;
  }
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 250);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function downloadTextFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// --- Full project takeoff export ---

export type TakeoffExportFormat = "pdf" | "csv" | "both";
export type TakeoffOrganizeBy = "room_floor" | "category" | "page";

export type TakeoffExportInclude = {
  aiCounts: boolean;
  manualCounts: boolean;
  finalCounts: boolean;
  confidence: boolean;
  planNotes: boolean;
  summaryTotals: boolean;
  lowConfidenceFlagged: boolean;
};

export type TakeoffExportProjectInput = {
  projectName: string;
  analyzedAt: Date;
  totalPagesScanned: number;
  /** PDF.js page counts per file, same order as `sheets`. */
  docNumPages: number[];
  sheets: Array<{ sheet_name: string; sheet_order: number }>;
  items: ElectricalItemRow[];
  rooms: DetectedRoomRow[];
  manualCounts: Record<string, number>;
  manualMode: boolean;
  /** If set, only these global page numbers */
  filterPages?: Set<number>;
  /** Single-room export */
  filterRoom?: Pick<DetectedRoomRow, "id" | "page_number" | "room_name">;
};

type PageSheetMeta = {
  globalPage: number;
  sheetNumber: number;
  sheetName: string;
};

function buildPageSheetIndex(
  sheets: TakeoffExportProjectInput["sheets"],
  docNumPages: number[],
): Map<number, PageSheetMeta> {
  const map = new Map<number, PageSheetMeta>();
  const ordered = [...sheets].sort((a, b) => a.sheet_order - b.sheet_order);
  let g = 1;
  for (let i = 0; i < ordered.length && i < docNumPages.length; i++) {
    const n = docNumPages[i];
    const sheetName = ordered[i].sheet_name;
    for (let lp = 0; lp < n; lp++) {
      map.set(g, {
        globalPage: g,
        sheetNumber: i + 1,
        sheetName,
      });
      g += 1;
    }
  }
  return map;
}

function roomSqFt(r: DetectedRoomRow): string {
  const w = r.width_ft != null ? Number(r.width_ft) : null;
  const len = r.length_ft != null ? Number(r.length_ft) : null;
  if (w != null && len != null && w > 0 && len > 0)
    return String(Math.round(w * len));
  if (r.sq_ft != null) {
    const s = Number(r.sq_ft);
    return Number.isFinite(s) && s > 0 ? String(Math.round(s)) : "";
  }
  return "";
}

function exportEffectiveQty(
  item: ElectricalItemRow,
  manualCounts: Record<string, number>,
  manualMode: boolean,
): number {
  if (manualMode) {
    const m = Math.round(Number(manualCounts[item.id] ?? 0));
    const ai = Math.round(Number(item.quantity));
    return m > 0 ? m : ai;
  }
  if (item.final_count != null) return Math.round(Number(item.final_count));
  return Math.round(Number(item.quantity));
}

function exportManualCountCell(
  item: ElectricalItemRow,
  manualCounts: Record<string, number>,
): string {
  const m = Math.round(Number(manualCounts[item.id] ?? 0));
  if (m > 0) return String(m);
  if (item.verification_status === "manual" && item.final_count != null) {
    return String(Math.round(Number(item.final_count)));
  }
  return "";
}

function exportPlanNoteText(item: ElectricalItemRow): string {
  if (item.category === "plan_note") {
    const raw = item.raw_note?.trim();
    if (raw) return raw;
  }
  return item.description ?? "";
}

function filterTakeoffData(input: TakeoffExportProjectInput): {
  items: ElectricalItemRow[];
  rooms: DetectedRoomRow[];
} {
  let items = input.items;
  let rooms = input.rooms;
  if (input.filterPages?.size) {
    items = items.filter((i) => input.filterPages!.has(i.page_number));
    rooms = rooms.filter((r) => input.filterPages!.has(r.page_number));
  }
  if (input.filterRoom) {
    const fr = input.filterRoom;
    const roomRow =
      input.rooms.find((r) => r.id === fr.id) ??
      input.rooms.find(
        (r) =>
          r.page_number === fr.page_number &&
          normalizeRoomLabel(r.room_name) === normalizeRoomLabel(fr.room_name),
      );
    if (roomRow) {
      items = items.filter(
        (i) =>
          i.page_number === roomRow.page_number &&
          itemMatchesDetectedRoom(i, roomRow),
      );
      rooms = [roomRow];
    } else {
      items = items.filter(
        (i) =>
          i.page_number === fr.page_number &&
          normalizeRoomLabel(displayWhichRoom(i)) ===
            normalizeRoomLabel(fr.room_name),
      );
      rooms = rooms.filter(
        (r) =>
          r.page_number === fr.page_number &&
          normalizeRoomLabel(r.room_name) === normalizeRoomLabel(fr.room_name),
      );
    }
  }
  return { items, rooms };
}

function sortItemsForOrganize(
  items: ElectricalItemRow[],
  rooms: DetectedRoomRow[],
  organizeBy: TakeoffOrganizeBy,
): ElectricalItemRow[] {
  const roomOrder = new Map<string, number>();
  const sortedRooms = [...rooms].sort((a, b) => {
    if (a.page_number !== b.page_number)
      return a.page_number - b.page_number;
    return a.room_name.localeCompare(b.room_name);
  });
  sortedRooms.forEach((r, idx) => {
    roomOrder.set(`${r.page_number}:${normalizeRoomLabel(r.room_name)}`, idx);
  });
  const key = (i: ElectricalItemRow): string => {
    const rn = normalizeRoomLabel(displayWhichRoom(i));
    const ro =
      roomOrder.get(`${i.page_number}:${rn}`) ??
      9999 + i.page_number * 100;
    if (organizeBy === "room_floor") {
      return `${String(i.page_number).padStart(5, "0")}-${String(ro).padStart(4, "0")}-${i.category}-${i.description}`;
    }
    if (organizeBy === "category") {
      return `${i.category}-${i.description}-${String(i.page_number).padStart(5, "0")}`;
    }
    return `${String(i.page_number).padStart(5, "0")}-${i.category}-${i.description}`;
  };
  return [...items].sort((a, b) => key(a).localeCompare(key(b)));
}

export function buildProjectTakeoffCsv(
  input: TakeoffExportProjectInput,
  organizeBy: TakeoffOrganizeBy,
  include: TakeoffExportInclude,
): string {
  const { items: rawItems, rooms: rawRooms } = filterTakeoffData(input);
  const pageIndex = buildPageSheetIndex(input.sheets, input.docNumPages);
  const items = sortItemsForOrganize(rawItems, rawRooms, organizeBy);
  const rooms = rawRooms;

  const headers = [
    "Project",
    "Sheet_Number",
    "Page_Number",
    "Room_Name",
    "Room_SqFt",
    "Category",
    "Description",
    "Specification",
    "AI_Count",
    "Manual_Count",
    "Final_Count",
    "Unit",
    "Confidence_Percent",
    "Verification_Status",
    "Plan_Note_Text",
    "Source_Page",
  ];
  const lines: string[] = [headers.join(",")];

  const roomSqByPageName = new Map<string, string>();
  for (const r of rooms) {
    roomSqByPageName.set(
      `${r.page_number}:${normalizeRoomLabel(r.room_name)}`,
      roomSqFt(r),
    );
  }

  const pct = (c: number) =>
    `${Math.round(Math.min(100, Math.max(0, Number(c) * 100)))}%`;

  for (const i of items) {
    const meta = pageIndex.get(i.page_number);
    const sheetNum = meta ? String(meta.sheetNumber) : "";
    const rn = displayWhichRoom(i);
    const sq =
      roomSqByPageName.get(
        `${i.page_number}:${normalizeRoomLabel(rn)}`,
      ) ?? "";
    const aiC = include.aiCounts ? String(Math.round(Number(i.quantity))) : "";
    const manC = include.manualCounts
      ? exportManualCountCell(i, input.manualCounts)
      : "";
    const finC =
      include.finalCounts && i.final_count != null
        ? String(Math.round(Number(i.final_count)))
        : include.finalCounts
          ? ""
          : "";
    const conf =
      include.confidence ? pct(Number(i.confidence)) : "";
    const pnote =
      include.planNotes ? exportPlanNoteText(i) : "";
    const row = [
      csvEscape(input.projectName),
      sheetNum,
      String(i.page_number),
      csvEscape(rn),
      csvEscape(sq),
      csvEscape(String(i.category ?? "")),
      csvEscape(String(i.description ?? "")),
      csvEscape(String(i.specification ?? "")),
      aiC,
      csvEscape(manC),
      finC,
      csvEscape(String(i.unit ?? "")),
      conf,
      csvEscape(String(i.verification_status ?? "")),
      csvEscape(pnote),
      String(i.page_number),
    ];
    lines.push(row.join(","));
  }

  const noteItems = items.filter((i) => i.category === "plan_note");
  if (include.planNotes && noteItems.length > 0) {
    lines.push(
      ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""].join(","),
    );
    lines.push(
      [
        csvEscape("PLAN_NOTES_SECTION"),
        "",
        "",
        "",
        "",
        "",
        csvEscape("Note text"),
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        csvEscape("Source_Page"),
      ].join(","),
    );
    for (const i of noteItems) {
      lines.push(
        [
          csvEscape(input.projectName),
          "",
          String(i.page_number),
          "",
          "",
          "plan_note",
          csvEscape(i.description ?? ""),
          csvEscape(i.specification ?? ""),
          "",
          "",
          "",
          "",
          "",
          "",
          csvEscape(exportPlanNoteText(i)),
          String(i.page_number),
        ].join(","),
      );
    }
  }

  if (include.lowConfidenceFlagged) {
    const low = items.filter((i) => Number(i.confidence) < 0.7);
    if (low.length > 0) {
      lines.push(
      ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""].join(","),
    );
      lines.push(
        [
          csvEscape("LOW_CONFIDENCE_SECTION"),
          "",
          "",
          "",
          "",
          "",
          csvEscape("Flagged item"),
          "",
          "",
          "",
          "",
          "",
          csvEscape("Confidence_Percent"),
          "",
          csvEscape("Source_Page"),
        ].join(","),
      );
      for (const i of low) {
        lines.push(
          [
            csvEscape(input.projectName),
            pageIndex.get(i.page_number)
              ? String(pageIndex.get(i.page_number)!.sheetNumber)
              : "",
            String(i.page_number),
            csvEscape(displayWhichRoom(i)),
            "",
            csvEscape(String(i.category ?? "")),
            csvEscape(i.description ?? ""),
            csvEscape(i.specification ?? ""),
            include.aiCounts ? String(Math.round(Number(i.quantity))) : "",
            include.manualCounts
              ? csvEscape(exportManualCountCell(i, input.manualCounts))
              : "",
            include.finalCounts && i.final_count != null
              ? String(Math.round(Number(i.final_count)))
              : "",
            csvEscape(String(i.unit ?? "")),
            pct(Number(i.confidence)),
            csvEscape(String(i.verification_status ?? "")),
            "",
            String(i.page_number),
          ].join(","),
        );
      }
    }
  }

  if (include.summaryTotals) {
    const qty = (i: ElectricalItemRow) =>
      exportEffectiveQty(i, input.manualCounts, input.manualMode);
    const sumCat = (cat: string) =>
      items
        .filter((i) => i.category === cat)
        .reduce((s, i) => s + qty(i), 0);
    const totalFix = sumCat("fixture");
    const totalPan = sumCat("panel");
    const totalWire = sumCat("wiring");
    const totalNotes = sumCat("plan_note");
    const grand = items.reduce((s, i) => s + qty(i), 0);
    const summaryRows: [string, number][] = [
      ["TOTAL_FIXTURES", totalFix],
      ["TOTAL_PANELS", totalPan],
      ["TOTAL_WIRING", totalWire],
      ["TOTAL_NOTES", totalNotes],
      ["GRAND_TOTAL", grand],
    ];
    lines.push(
      ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""].join(","),
    );
    for (const [label, val] of summaryRows) {
      lines.push(
        [
          csvEscape(input.projectName),
          "",
          "",
          "",
          "",
          csvEscape("SUMMARY"),
          csvEscape(label),
          "",
          "",
          "",
          String(val),
          "",
          "",
          "",
          "",
          "",
        ].join(","),
      );
    }
  }

  return lines.join("\r\n");
}

export function openProjectTakeoffPrintReport(
  input: TakeoffExportProjectInput,
  organizeBy: TakeoffOrganizeBy,
  include: TakeoffExportInclude,
): void {
  const { items: rawItems, rooms: rawRooms } = filterTakeoffData(input);
  const pageIndex = buildPageSheetIndex(input.sheets, input.docNumPages);
  const items = sortItemsForOrganize(rawItems, rawRooms, organizeBy);
  const rooms = [...rawRooms].sort((a, b) => {
    if (a.page_number !== b.page_number)
      return a.page_number - b.page_number;
    return a.room_name.localeCompare(b.room_name);
  });

  const qty = (i: ElectricalItemRow) =>
    exportEffectiveQty(i, input.manualCounts, input.manualMode);

  const byCat = (cat: string) =>
    items.filter((i) => i.category === cat).reduce((s, i) => s + qty(i), 0);

  const catTableRows = [
    ["fixture", "Fixtures", byCat("fixture")],
    ["panel", "Panels", byCat("panel")],
    ["wiring", "Wiring", byCat("wiring")],
    ["plan_note", "Plan notes", byCat("plan_note")],
  ]
    .map(
      ([, label, n]) =>
        `<tr><td>${escapeHtml(String(label))}</td><td class="num">${n}</td></tr>`,
    )
    .join("");

  const deviceItems = items.filter((i) => i.category !== "plan_note");
  const totalDevices = deviceItems.reduce((s, i) => s + qty(i), 0);

  const roomSummaryRows = rooms
    .map((r) => {
      const sq = roomSqFt(r);
      return `<tr><td>${escapeHtml(r.room_name)}</td><td>${escapeHtml(r.room_type)}</td><td>${sq ? escapeHtml(sq) : "—"}</td><td class="num">${r.page_number}</td></tr>`;
    })
    .join("");

  const pagesAnalyzed = new Set(items.map((i) => i.page_number)).size;
  const unverified = items.filter((i) => {
    const s = i.verification_status ?? "pending";
    return s === "pending" || s === "review_needed" || s === "conflict";
  });

  const itemRowHtml = (i: ElectricalItemRow) => {
    const desc = escapeHtml(i.description);
    const spec = escapeHtml(i.specification ?? "");
    const qAi = include.aiCounts ? String(Math.round(Number(i.quantity))) : "—";
    const qMan = include.manualCounts
      ? exportManualCountCell(i, input.manualCounts) || "—"
      : "—";
    const qFin =
      include.finalCounts && i.final_count != null
        ? String(Math.round(Number(i.final_count)))
        : "—";
    const conf = include.confidence
      ? `${Math.round(Number(i.confidence) * 100)}%`
      : "—";
    const ver = escapeHtml(String(i.verification_status ?? ""));
    const notes = include.planNotes ? escapeHtml(exportPlanNoteText(i)) : "—";
    return `<tr class="${Number(i.confidence) < 0.7 ? "low" : ""}"><td>${desc}</td><td>${spec}</td><td class="num">${qAi}</td><td class="num">${qMan}</td><td class="num">${qFin}</td><td class="num">${conf}</td><td>${ver}</td><td>${notes}</td></tr>`;
  };

  const roomBlocks = rooms
    .map((r) => {
      const inRoom = items.filter(
        (i) =>
          i.page_number === r.page_number &&
          itemMatchesDetectedRoom(i, r) &&
          normalizeRoomLabel(displayWhichRoom(i)) !== "UNASSIGNED",
      );
      const sub = inRoom.reduce((s, i) => s + qty(i), 0);
      const sq = roomSqFt(r);
      const meta = pageIndex.get(r.page_number);
      const sheetLine = meta
        ? `Sheet ${meta.sheetNumber} (${escapeHtml(meta.sheetName)}) · Page ${r.page_number}`
        : `Page ${r.page_number}`;
      const rows = inRoom.map(itemRowHtml).join("") || "<tr><td colspan='8'>No items</td></tr>";
      return `<section class="sheet"><h2>${escapeHtml(r.room_name)}</h2><p class="meta">${sq ? escapeHtml(sq) + " sq ft · " : ""}${sheetLine}</p><table><thead><tr><th>Description</th><th>Spec</th><th>AI qty</th><th>Manual</th><th>Final</th><th>Conf.</th><th>Verified</th><th>Notes</th></tr></thead><tbody>${rows}</tbody></table><p class="subtotal"><strong>Room subtotal:</strong> ${sub}</p></section>`;
    })
    .join("");

  const planNotes = items.filter((i) => i.category === "plan_note");

  const notesSection = !include.planNotes
    ? ""
    : planNotes.length > 0
      ? `<section class="sheet"><h2>Plan notes</h2><h3>Electrical notes (verbatim / quoted)</h3><ul>${planNotes
          .filter((i) => i.raw_note?.trim())
          .map(
            (i) =>
              `<li><span class="meta">Page ${i.page_number}</span> — ${escapeHtml(exportPlanNoteText(i))}</li>`,
          )
          .join("")}</ul><h3>General plan notes</h3><ul>${planNotes
          .filter((i) => !i.raw_note?.trim())
          .map(
            (i) =>
              `<li><span class="meta">Page ${i.page_number}</span> — ${escapeHtml(i.description)}</li>`,
          )
          .join("")}</ul></section>`
      : `<section class="sheet"><h2>Plan notes</h2><p class="meta">No plan notes in export scope.</p></section>`;

  const lowBlock =
    include.lowConfidenceFlagged && items.some((i) => Number(i.confidence) < 0.7)
      ? `<section class="sheet"><h2>Low confidence items</h2><ul>${items
          .filter((i) => Number(i.confidence) < 0.7)
          .map(
            (i) =>
              `<li>Page ${i.page_number}: ${escapeHtml(i.description)} (${Math.round(Number(i.confidence) * 100)}%)</li>`,
          )
          .join("")}</ul></section>`
      : "";

  const summaryFooter =
    include.summaryTotals
      ? `<section class="sheet"><h2>Summary totals</h2><table><tbody>
<tr><td>TOTAL_FIXTURES</td><td class="num">${byCat("fixture")}</td></tr>
<tr><td>TOTAL_PANELS</td><td class="num">${byCat("panel")}</td></tr>
<tr><td>TOTAL_WIRING</td><td class="num">${byCat("wiring")}</td></tr>
<tr><td>TOTAL_NOTES</td><td class="num">${byCat("plan_note")}</td></tr>
<tr><td><strong>GRAND_TOTAL</strong></td><td class="num"><strong>${items.reduce((s, i) => s + qty(i), 0)}</strong></td></tr>
</tbody></table></section>`
      : "";

  const title = escapeHtml(`${input.projectName} — Takeoff`);
  const when = escapeHtml(input.analyzedAt.toLocaleString());
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${title}</title>
<style>
@page { margin: 16mm; }
body{font-family:system-ui,sans-serif;color:#111;line-height:1.45;margin:0}
.sheet{page-break-after:always;padding:16px 20px}
.sheet:last-child{page-break-after:auto}
.cover{text-align:center;padding-top:48px}
.logo-ph{border:2px dashed #999;width:180px;height:72px;margin:24px auto;display:flex;align-items:center;justify-content:center;color:#666;font-size:14px}
h1{font-size:1.5rem} h2{font-size:1.15rem;margin:0 0 10px} h3{font-size:1rem;margin:12px 0 6px}
.meta{color:#444;font-size:0.88rem}
table{width:100%;border-collapse:collapse;font-size:0.82rem;margin-top:8px}
th,td{border:1px solid #ccc;padding:5px 7px;text-align:left}
th{background:#f0f0f0}
.num{text-align:right}
tr.low{background:#fff9c4}
.subtotal{margin-top:10px;font-size:0.95rem}
footer{font-size:0.78rem;color:#666;margin-top:12px}
ul{margin:0;padding-left:1.2rem}
</style></head><body>
<section class="sheet cover">
<div class="logo-ph">${escapeHtml(COMPANY)} — logo</div>
<h1>Electrical Takeoff Report</h1>
<p class="meta"><strong>Project:</strong> ${escapeHtml(input.projectName)}</p>
<p class="meta"><strong>Date analyzed:</strong> ${when}</p>
<p class="meta"><strong>Total pages scanned:</strong> ${input.totalPagesScanned}</p>
<footer>${escapeHtml(FOOTER)}</footer>
</section>
<section class="sheet"><h1>Executive summary</h1>
<h2>Total items by category</h2>
<table><thead><tr><th>Category</th><th>Count</th></tr></thead><tbody>${catTableRows}</tbody></table>
<p class="meta" style="margin-top:14px"><strong>Total devices (excl. note lines):</strong> ${totalDevices}</p>
<h2>Rooms detected</h2>
<table><thead><tr><th>Room</th><th>Type</th><th>Sq ft</th><th>Page</th></tr></thead><tbody>${roomSummaryRows || "<tr><td colspan='4'>No rooms</td></tr>"}</tbody></table>
<p class="meta"><strong>Pages with line items:</strong> ${pagesAnalyzed}</p>
${unverified.length ? `<h2>Unverified / needs review</h2><ul>${unverified.slice(0, 40).map((i) => `<li>Page ${i.page_number}: ${escapeHtml(i.description)} (${escapeHtml(String(i.verification_status ?? ""))})</li>`).join("")}${unverified.length > 40 ? `<li>… and ${unverified.length - 40} more</li>` : ""}</ul>` : "<p class=\"meta\">No unverified items flagged.</p>"}
</section>
${roomBlocks || `<section class="sheet"><p>No room-grouped items in export scope.</p></section>`}
${notesSection}
${lowBlock}
${summaryFooter}
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) {
    window.alert("Pop-up blocked. Allow pop-ups to print the PDF report.");
    return;
  }
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}

export function runTakeoffExport(
  input: TakeoffExportProjectInput,
  format: TakeoffExportFormat,
  organizeBy: TakeoffOrganizeBy,
  include: TakeoffExportInclude,
): void {
  const stamp = input.analyzedAt.toISOString().slice(0, 10);
  const safeName = input.projectName.replace(/[^\w\- ]+/g, "").trim() || "project";
  if (format === "csv" || format === "both") {
    const csv = buildProjectTakeoffCsv(input, organizeBy, include);
    downloadTextFile(
      `takeoff-${safeName}-${stamp}.csv`,
      csv,
      "text/csv;charset=utf-8",
    );
  }
  if (format === "pdf" || format === "both") {
    openProjectTakeoffPrintReport(input, organizeBy, include);
  }
}
